# Generated by Django 3.2.9 on 2021-11-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
