# Generated by Django 3.2.9 on 2021-11-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211108_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_owner',
            field=models.CharField(default='foobar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='is_observer',
            field=models.BooleanField(default=False),
        ),
    ]
