# Generated by Django 3.2.9 on 2021-11-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211109_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='phase',
            field=models.CharField(choices=[('0-lobby', '0 Lobby'), ('1-starting', '1 Starting'), ('2-live', '2 Live'), ('3-complete', '3 Complete')], default='0-lobby', max_length=12),
        ),
    ]
