# Generated by Django 3.2.9 on 2021-11-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pid',
            field=models.PositiveSmallIntegerField(default=8001),
            preserve_default=False,
        ),
    ]
