# Generated by Django 3.2.9 on 2022-03-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_room_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleMap',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('meters_x', models.PositiveBigIntegerField()),
                ('meters_y', models.PositiveBigIntegerField()),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BattleMapFeature',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('position_meters_x', models.PositiveBigIntegerField()),
                ('position_meters_y', models.PositiveBigIntegerField()),
                ('width_meters_x', models.PositiveSmallIntegerField()),
                ('width_meters_y', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('type', models.CharField(choices=[('fuel', 'Fuel'), ('ore', 'Ore')], max_length=12)),
                ('battle_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.battlemap')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='room',
            name='battle_map',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.battlemap'),
        ),
    ]
