# Generated by Django 3.2.9 on 2022-03-19 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220319_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlemap',
            name='is_draft',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='battlemap',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='battlemapfeature',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BattleMapSpawnPoint',
            fields=[
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_meters_x', models.PositiveBigIntegerField()),
                ('position_meters_y', models.PositiveBigIntegerField()),
                ('battle_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.battlemap')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
