# Generated by Django 3.2.9 on 2022-03-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220319_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlemapfeature',
            name='type',
            field=models.CharField(choices=[('station', 'Station'), ('ore', 'Ore')], max_length=12),
        ),
    ]
