# Generated by Django 3.2.9 on 2022-03-26 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_battlemapfeature_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMiningLocation',
            fields=[
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_meters_x', models.PositiveBigIntegerField()),
                ('position_meters_y', models.PositiveBigIntegerField()),
                ('service_radius_meters', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('battle_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.battlemap')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapSpaceStation',
            fields=[
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_meters_x', models.PositiveBigIntegerField()),
                ('position_meters_y', models.PositiveBigIntegerField()),
                ('service_radius_meters', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('battle_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.battlemap')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BattleMapFeature',
        ),
    ]
