# Generated by Django 3.2.9 on 2022-03-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220326_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmininglocation',
            name='starting_ore_amount_kg',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
