# Generated by Django 3.2.9 on 2022-10-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20221017_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ship_asset_name',
            field=models.CharField(default='type_1_gray', max_length=32),
            preserve_default=False,
        ),
    ]
