# Generated by Django 3.2.9 on 2022-10-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_player_ship_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ship_asset_name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
